services:
  mysqldb:
    image: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3307
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always

  notification_app:
    container_name: notification_service
    build: .
    ports:
      - ${SERVICE_PORT}:8080
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}


    depends_on:
      - mysqldb
    restart: on-failure